//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenBack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesOrden
    {
        public int id_detalle_orden { get; set; }
        public Nullable<int> id_orden { get; set; }
        public Nullable<int> id_reloj { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
        public virtual Relojes Relojes { get; set; }
    }
}
